- .github/actions/f3d-superbuild/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
https://github.com/f3d-app/f3d/issues/524
> Better release workflow

- .github/workflows/nightly.yml
Modify nightly check for a more solid approach
> Modify nightly check

- projects/draco.cmake
- projects/patches/draco-fix-signed-unsigned-mismatch-warning-in-decoder_buff.patch
Not needed on the CI for some reason but needed locally on Windows.
> Add a patch from draco master to fix a build issue with draco

- .github/actions/f3d-superbuild/action.yml
- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- projects/f3d.bundle.common.cmake
- projects/f3d.suffix.cmake
- testing/CMakeLists.txt
- Improve CI in general
- Improve package suffix
- Provide a raytracing and a non raytracing package
- Fix https://github.com/f3d-app/f3d/issues/594
> Raytracing packaging and CI improvements

- .github/workflows/nightly.yml
- Secret token was non fonctionnal fixing it in a location where it actually works
- Nightly tag advanvement was incorrectly done before build and package, fixing that too
> Fix nightly tag advancement

- projects/win32/f3d.bundle.cmake
Fix https://github.com/f3d-app/f3d/issues/628
> Add json parsing in nsis packaging

- projects/f3d.cmake
- projects/win32/f3d.bundle.cmake
- Install json files so that the thumbnailers works as expected
- Install files from /etc/share
- Fix logo.ico location
> Handle resources on windows

- .github/actions/f3d-superbuild/action.yml
- CMakeLists.txt
- projects/occt.cmake
- testing/CMakeLists.txt
- testing/baselines/TestOCCT.png
- testing/baselines/TestOCCTColoring.png
- testing/data/f3d.stp
- Enable coloring modules in occt
- Add testing
- Fix https://github.com/f3d-app/f3d/issues/762
> Add coloring support for step files

- .github/workflows/nightly.yml
`config` is not compatible with `include` and actually not needed. switching to `include` and `config` would require way to many configs to be viable.
> fix nightly

- projects/apple/f3d.bundle.cmake
- projects/f3d.bundle.common.cmake
- projects/unix/f3d.bundle.cmake
- projects/win32/f3d.bundle.cmake
Need to patch the `common-superbuild` first.
[component.patch](https://github.com/f3d-app/f3d-superbuild/files/12782913/component.patch)
Fix https://github.com/f3d-app/f3d-superbuild/issues/113 and https://github.com/f3d-app/f3d/issues/1021
> Remove SB components

- .github/actions/f3d-superbuild/action.yml
- .github/actions/wheels/action.yml
Rollback superbuild update because of https://gitlab.kitware.com/paraview/common-superbuild/-/issues/70
> rollback superbuild update

- .github/actions/wheels/action.yml
- .github/actions/wheels/test_with_pytest_retry.sh
A work around for https://github.com/pytest-dev/pytest/issues/11647
> Retry pytest on fail to avoid flaky errors

- projects/unix/f3d.bundle.cmake
Fix https://github.com/f3d-app/f3d/issues/1099
> Fix DEB package for EGL version

- .github/actions/wheels/action.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
Publish on pypi using trusted publishing
Publish nightly on testpypi
Publish release on pypi
Example of "sucessful" run: https://github.com/f3d-app/f3d-superbuild/actions/runs/7358146730/job/20031219551?pr=136
> Automatically publish to pypi and testpypi

- .github/actions/wheels/action.yml
Related to https://github.com/pypa/cibuildwheel/issues/1740
> wheel: Update cibuildwheel to fix it

- .github/workflows/nightly.yml
- .github/workflows/release.yml
Make release and nightly works as CI for macOS arm64
> CI: Finish arm64 nightly and release setup

- .github/workflows/nightly.yml
Fix #https://github.com/f3d-app/f3d/issues/1236
> Run nightly only on f3d-app

- .github/workflows/ci.yml
> Cleanup macos ci

- .github/actions/wheels/action.yml
more info: https://github.com/pypa/cibuildwheel/issues/1809
> CI: Use repair default value for cibuildwheel

- .github/workflows/nightly.yml
- .github/workflows/release.yml
Follow up of https://github.com/f3d-app/f3d-superbuild/pull/163
> CI: Fix nightly and release workflow for macOS arm64

- .github/actions/f3d-superbuild/action.yml
- .github/workflows/ci.yml
- Use LFS data cache
- Disable LFS during build
> Improve LFS usage in CI

- .github/actions/f3d-superbuild/action.yml
- .github/workflows/nightly.yml
- make lfs_sha optional so that release job do not care about it
- add correct lfs support to nightly
> Fix lfs action

- versions.cmake
Fix https://github.com/f3d-app/f3d-superbuild/issues/205
> versions: Add F3D 2.5.1 and VTK 9.4.0

- .github/actions/wheels/action.yml
- .github/actions/wheels/build_f3d_superbuild.sh
Fix https://github.com/f3d-app/f3d/issues/1788
> Wheels: Enable EGL and osmesa in python wheels

- testing/CMakeLists.txt
- ref -> reference
- samples -> raytracing-samples
> Test: Update for new CLI option in F3D

- CMakeLists.txt
- projects/f3d.cmake
- projects/f3dhdf.cmake
- projects/vtk.cmake
cf https://github.com/f3d-app/f3d/pull/2170
> Activate HDF plugin

- testing/CMakeLists.txt
https://github.com/f3d-app/f3d-superbuild/issues/256
> Tests: Disabling TestExternal

- .github/workflows/nightly.yml
- .github/workflows/release.yml
- Add package asset to nightly and release page
- Add automatic NPM publish on release
> Add wasm nightly package and release
